name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add bitnami charts
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Add bjw-s charts
        run: |
          helm repo add bjw-s https://bjw-s.github.io/helm-charts

      - name: Remove readme images
        run: |
          set -x
          for f in charts/**/README.md; do
            sed -i '/^<img .* alt=".* logo"/,+1d' "$f"
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ github.token }}"
          CR_SKIP_EXISTING: "true"
          CR_PAGES_BRANCH: helm-index
