name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add charts repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add bjw-s https://bjw-s.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ github.token }}"
          CR_SKIP_EXISTING: "true"
          CR_PAGES_BRANCH: helm-index
